### ISSUE TITLE
Apple Music

### ISSUE THREAD

**Issue by benortiz** [flowtsohg/youtube-song-names-for-obs#3]
Hey @flowtsohg,

Thanks for this great plugin! I ended up using your code as a foundation for an [Apple Music plugin](https://addons.mozilla.org/en-US/firefox/addon/applemusic-web-for-obs/) that works very similarly. I think I got the [license](https://git.sr.ht/~toastronaut/apple-music-web-obs) right, but let me know if you see something I should change. Again, thanks for making your plugin open and all of your work maintaining it.

**Comment by flowtsohg** [comment]
One year late, but nice work!
